jobs: 24
cluster: sbatch
use-conda: true
cluster: "sbatch -t {resources.time_min} --mem={resources.mem_mb} -c {resources.cpus} -o /liulab/alynch/logs/{rule}_{wildcards} -e /liulab/alynch/logs/{rule}_{wildcards} --mail-type=FAIL --mail-user=alynch@ds.dfci.harvard.edu"
default-resources: [cpus=1, mem_mb=2000, time_min=60]
resources: [cpus=24, mem_mb=24000]